### ISSUE TITLE
SDK throwing a System.UriFormatException.

### ISSUE THREAD

**Issue by Danthekilla** [Countly/countly-sdk-windows#10]
I recently integrated Countly into our latest game and we rarely are getting these exceptions happening and crashing our game to desktop. 

Can everything in Countly please be fully wrapped in error handling or suppression as it is frustrating to have our crash logging system crashing our game.

Here is the error, I don't really have any more info on this one, it seems to be random.

```
Unhandled Exception: System.UriFormatException: Invalid URI: The Uri string is too long.
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at CountlySDK.Countly.<>c__DisplayClass46_0.<<AddEvent>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
The program '[30056] BlockGame.exe' has exited with code 0 (0x0).
```

**Comment by ArtursKadikis** [comment]
Hello, this seems crash seems to me to be related to the threading issue. Could you try the fixed version from this commit (https://github.com/Countly/countly-sdk-windows/tree/b5f0cca5b6d9997d879eea0488d52d962a61acfc)? There is another outstanding issue that needs to be fixed before we can release it, since the problem involves nuget.

**Comment by ArtursKadikis** [comment]
If that does not help, could you maybe try making all countly related calls from the same thread?

**Comment by ArtursKadikis** [comment]
Hello, we just released a new version of the sdk. Could you please check if the problem is fixed?
