### ISSUE TITLE
SDK throwing a "COLLECTION WAS MODIFIED; ENUMERATION OPERATION MAY NOT EXECUTE." exception

### ISSUE THREAD

**Issue by Danthekilla** [Countly/countly-sdk-windows#9]
I recently integrated countly into our latest game and we keep getting lots of these exceptions coming in via countlys crash tracking. Is this something we are doing or a bug in the API?

This is the exception:

COLLECTION WAS MODIFIED; ENUMERATION OPERATION MAY NOT EXECUTE.
`at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at CountlySDK.Countly.<>c__DisplayClass46_0.<<AddEvent>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() ::: Environment.StackTrace :::    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)`

**Comment by ArtursKadikis** [comment]
Hello, on which operating system was the game was running? Do you maybe know anything more about the circumstances of the exceptions? Is your game multithreaded? Do you use any frameworks for your game?

**Comment by Danthekilla** [comment]
Hey,

These crashes have been coming from windows 7, 8.1 and 10.

Our game is multithreaded.

Here is a rough list of the frameworks and dlls that we use:
![image](https://user-images.githubusercontent.com/2770203/34975680-0bd63a68-fae7-11e7-8276-868bceed038b.png)

**Comment by Danthekilla** [comment]
Has there been any progress on this issue? This is preventing our launch.

**Comment by Danthekilla** [comment]
This is great to hear, we are launching our game (moving out of beta) early next week so this is great news.

We have also had another error recently come up every now and then. #10

**Comment by ArtursKadikis** [comment]
Hello, we just released a new version of the sdk. Could you please check if the problem is fixed?
